config/routes.rb
Hackathonbuza::Application.routes.draw do
  get "pages/home"

  resources :countries

  root 'pages#home'

  

end

app/models/consulate.rb
class Consulate < ActiveRecord::Base
  belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_one :report
	has_one :prisoner
	has_many :dangers
  has_many :consulates

  def cool_title(danger)
    if danger
      case danger.title
        when 'oorlog'
          return "Oorlogje Spelen in #{ self.title }"
        when 'rebellen'
          return "Anarchie in #{ self.title }"
        when 'piraterij'
          return "Piraterij in #{ self.title }"
        when 'geweld'
          return "Ruw Geweld in #{ self.title }"
        when 'carjacking'
          return "Joyriden in #{ self.title }"
        when 'afpersing'
          return "Afpersen in #{ self.title }"
        when 'aardbeving'
          return "Aardbeving in #{ self.title }"
        when 'orkaan'
          return "Stormchasen in #{ self.title }"
        when 'lawine'
          return "Lawinegevaar in #{ self.title }"
        when 'beroving'
          return "Struikroven in #{ self.title }"
        when 'brand'
          return "Vuurtje Stoken in #{ self.title }"
        when 'verkeer'
          return "Rally-rijden in #{ self.title }"
        when 'cycloon'
          return "Waterhoossurfen in #{ self.title }"
        when 'demonstratie'
          return "Demonstreer mee in #{ self.title }"
        when 'overstroming'
          return "Waterpark in #{ self.title }"
        when 'wegen'
          return "Jeep Safari in #{ self.title }"
        when 'terrorist'
          if self.classification.to_i < 3
            return ["Kamperen in #{ self.title }", "Bungalow in #{ self.title }", "Citytrip naar #{ self.title }", "Backpacken in #{ self.title }"].sample
          elsif self.classification.to_i >= 3
            return "Heilige Oorlog Voeren in #{ self.title }"
          else
            return self.title
          end
        else
          return self.title
      end

    end

    self.title 

  end

  def death_rating
    if self.deaths.nil?
      return 1
    elsif self.deaths > 40
      return 5
    elsif self.deaths > 25 
      return 4
    elsif self.deaths > 10
      return 3
    elsif self.deaths > 0
      return 2
    end
    return 1
  end

  def class_image
    classes = ["beginner", "gevorderd", "veteraan", "ramptoerist"]
    return "#{ classes[self.classification.to_i - 1] }2.png"
  end

  def reisleider
    reisleiders = ["barry", "robin", "boy"]
    return "#{ reisleiders.sample }.png"
  end


end

app/models/danger.rb
class Danger < ActiveRecord::Base
  belongs_to :country
end

app/models/prisoner.rb
class Prisoner < ActiveRecord::Base
  belongs_to :country
end

app/models/report.rb
class Report < ActiveRecord::Base
	 belongs_to :country
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render action: 'show', status: :created, location: @country }
      else
        format.html { render action: 'new' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params[:country]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @countries = Country.find(:all, :order => 'title ASC' )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/countries/_form.html.erb
<%= form_for(@country) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<div class="country-header" style="background-image: url(<%= image_path(@country.class_image) %>);">
  <h1><%= @country.title %></h1>
  <p class="leader"><%= @country.cool_title(@country.dangers.sample) %></p>
</div>

<div class="container">
  <%= link_to (raw "&larr; Terug naar het overzicht"), root_path %>
  <div class="row">
    <div class="span10 offset1 country-content">
      <%= link_to 'Boek Nu!', '#', { :class => 'btn btn-large btn-warning pull-right' } %>
      <h3>Algemeen</h3>
      <%= raw @country.report.algemeen %>
      <h3>Actueel</h3>
      <%= raw @country.report.actueel %>
      <h3>Terrorisme</h3>
      <%= raw @country.report.terrorisme %>
      <h3>Criminaliteit</h3>
      <%= raw @country.report.criminaliteit %>
      <h3>Gebieden</h3>
      <%= raw @country.report.gebieden %>
    </div>
    <div class="span8 offset2 contact">
      <% if @country.consulates.first %>
        <div class="travel-guide clearfix">
          <h1>Mocht het niet allemaal goed aflopen of je hebt hulp nodig tijdens je permanente verblijf.<br/>
            <% if !@country.consulates.first.telephone.nil? %>
              <small>Dan kun je mij altijd 24/7 bereiken op <%= @country.consulates.first.telephone %></small>
            <% end %>
          </h1>
          <div class="thumbnail">
            <%= image_tag @country.reisleider %>
          </div>
          <dl>
            <dt>Reisleider:</dt>
            <dd><%= @country.consulates.first.contact %></dd>
            <dd><a href="mailto:<%= @country.consulates.first.mail %>"><%= @country.consulates.first.mail %></a></dd>
          </dl>
        </div>
      <% end %>
    </div>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <title><%= content_for?(:title) ? yield(:title) : "THRILLSEEKER" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42278099-1', 'herokuapp.com');
    ga('send', 'pageview');
    </script>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'THRILLSEEKER', root_path, { :class => 'brand' } %>
          <div class="container nav-collapse pull-right">
            <ul class="nav">
              <li><%= link_to "Informatie", root_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <%= bootstrap_flash %>
    <%= yield %>

    <div class="container">
      <footer>
        <p>&copy; Gemaakt op vakantie door <a href="https://twitter.com/boyvanamstel">@boyvanamstel</a>, <a href="https://twitter.com/raldenhoven">@raldenhoven</a>, <a href="https://twitter.com/barryborsboom">@barryborsboom</a> tijdens <a href="https://twitter.com/HackathonBuZa">Hackathon BuZa</a></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/home.html.erb
<div id="slider">
  <%= image_tag 'beginner.png', :id => 'slider-image-beginner', :class => 'slider-image' %>
  <%= image_tag 'gevorderd.png', :id => 'slider-image-gevorderd', :class => 'slider-image' %>
  <%= image_tag 'veteraan.png', :id => 'slider-image-veteraan', :class => 'slider-image' %>
  <%= image_tag 'ramptoerist.png', :id => 'slider-image-ramptoerist', :class => 'slider-image' %>
  <div id="slider-container">
    <input id="slider-element" type="range" value="1" min="1" max="4" step='.01' class="slider" />
    <ul>
      <li><h3>Beginner</h3></li>
      <li><h3>Gevorderde</h3></li>
      <li><h3>Veteraan</h3></li>
      <li><h3>Ramptoerist</h3></li>
    </ul>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="span12">
      <ul id="countries">
        <% @countries.each do |country| %>
        <% danger = country.dangers.sample %>
        <li class="country classification_<%= country.classification %>">
          <div>
            <div class="row divider">
              <div class="image span3">
                <% if danger %>
                  <% if country.classification.to_i >= 3 and danger.title == 'terrorist' %>
                    <%= image_tag "icons/heiligeoorlog.png", :alt => danger.title %>
                  <% else %>
                    <%= image_tag "icons/#{ danger.title }.png", :alt => danger.title %>
                  <% end %>
                <% end %>
              </div>
              <div class="span9 meta">
                <h2><%= link_to "#{ country.cool_title(danger) }", country_path(country) %></h2>
                <div class="info">
                  <% if defined? country.report %>
                    <p><%= truncate(strip_tags(country.report.algemeen), length: 250) %>
                  <% end %>
                </div>
                <ul class="stats row">
                  <li class="span3 temp">
                    <% if country.weather_main %>
                      <%= image_tag "#{ country.weather_main.downcase }.png", :alt => country.weather_main %>
                    <% else %>
                      <%= image_tag "clear.png", :alt => 'clear' %>
                    <% end %>
                    <% if country.weather_temp %>
                      <%= country.weather_temp %>°C
                    <% else %>
                      ?
                    <% end %>
                  </li>
                  <li class="span3 prison">
                    <%= image_tag 'icons/gevangen.png', :alt => 'gevangenen' %>
                    <% if defined? country.prisoner.count %>
                      <%= country.prisoner.count %>
                    <% else %>
                      ? 
                    <% end %>
                  </li>
                  <li class="span3">
                    <ul class="death-rating pull-right">
                      <% for i in 1..country.death_rating %>
                        <li><%= image_tag 'dood2.png', :class => 'filled' %></li>
                      <% end %>
                      <% for i in 1..(5 - country.death_rating) %>
                        <li><%= image_tag 'dood1.png' %></li>
                      <% end %>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
            <div class="row buttons">
              <% if country.price.to_i != 0 %>
                <% price_link = "Boek Nu!" %>
              <% else %>
                <% price_link = "Vraag Een Offerte Aan" %>
              <% end %>
              <%= link_to (raw price_link), country_path(country), { :class => 'btn btn-large btn-warning pull-right' } %>
              <% if country.price.to_i != 0 %>
                <strong class="pull-right price-caption"><%= raw "Van <strike>€ #{ country.price + rand(100) }</strike> voor <span class='discount'>€ #{ country.price }</span>" %></strong>
              <% end %>
              <%= image_tag 'icons/vliegtuig.png', { :class => 'pull-right' } %>
            </div>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>